
# baseURL = "https://nat-mcaleese.co.uk"
baseURL = "https://festive-spence-7d2cc9.netlify.com/"
languageCode = "en-uk"
title = "My New Hugo Site"
pygmentsCodeFences = true

[params]
  blogTitle = "Blog"

[permalinks]
  posts = "/:year/:monthname/:title/"
